name: Build Release Android APK
on:
  push:
	branches: [ "master" ]
 
jobs:
  Build-Release-Android-APK:
	runs-on: "ubuntu-latest"
	if: "contains(github.event.head_commit.message, 'android')"
	
	steps:
  	### This job to clone the code
  	- name: "Checkout Code"
    	uses: actions/checkout@v3
    	
  	### This job to setup NodeJs on your Ubuntu Machine
  	- name: "Setup NODE"
    	uses: actions/setup-node@v3
    	with:
          node-version: 18
 
  	### This job to install Nodejs Dependencies
  	- name: "Install Node Dependencies"
    	run: |
      	npm i
 
  	### This job to Build  Android APK  	
  	- name: "Build and Release"
    	run: |
      	cd android
      	chmod a+x gradlew
      	./gradlew build
      	./gradlew assembleRelease
      	./gradlew app:bundleRelease
    	env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      	  KEY_ALIAS: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      	
  	### This job to Upload APK to AppCenter
  	- name: "upload apk to App Center"
    	uses: wzieba/AppCenter-Github-Action@v1
    	with:
      	appName: "srinivasan-vthink.co.in/React-App"
      	token: ${{secrets.APP_CENTER_TOKEN}}
      	file: ./android/app/build/outputs/apk/release/app-release.apk
      	group: "tester"
      	notifyTesters: "true"
